function makeNewYork(){
    var background =document.getElementById('background')
    background.setAttribute("src","#newYork")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",true)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false) 
    document.getElementById('newYorkText').setAttribute("visible",true)
    document.getElementById('sydneyText').setAttribute("visible",false)
    document.getElementById('parisText').setAttribute("visible",false)
    document.getElementById('indonesiaText').setAttribute("visible",false)
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
    
    
}
function makeSydney(){
    var background =document.getElementById('background')
    background.setAttribute("src","#sydney")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false) 
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false) 
    document.getElementById('sydneyTitle').setAttribute("visible",true)
    document.getElementById('newYorkText').setAttribute("visible",false)
    document.getElementById('sydneyText').setAttribute("visible",true)
    document.getElementById('parisText').setAttribute("visible",false)
    document.getElementById('indonesiaText').setAttribute("visible",false)
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
}
function makeParis(){
    var background =document.getElementById('background')
    background.setAttribute("src","#paris")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",true)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)  
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false) 
    document.getElementById('newYorkText').setAttribute("visible",false)
    document.getElementById('sydneyText').setAttribute("visible",false)
    document.getElementById('parisText').setAttribute("visible",true)
    document.getElementById('indonesiaText').setAttribute("visible",false)
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
}
function makeColumbia(){
    var background =document.getElementById('background')
    background.setAttribute("src","#columbia")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",true)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false)
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", true)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
    
}
function makeIndonesia(){
    var background =document.getElementById('background')
    background.setAttribute("src","#indonesia")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",true)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false)
    document.getElementById('newYorkText').setAttribute("visible",false)
    document.getElementById('sydneyText').setAttribute("visible",false)
    document.getElementById('parisText').setAttribute("visible",false)
    document.getElementById('indonesiaText').setAttribute("visible",true)
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
}
function makeFiji(){
    var background =document.getElementById('background')
    background.setAttribute("src","#fiji")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",true)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false)  
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",true)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
    
}

function makeRussia(){
    var background =document.getElementById('background')
    background.setAttribute("src","#russia")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",true) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false)  
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
    
}

function makeJapan(){
    var background =document.getElementById('background')
    background.setAttribute("src","#japan")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",true)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false)
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", true)
    document.getElementById('egyptText').setAttribute("visible", false)
    
    
}

function makeEgypt(){
    var background =document.getElementById('background')
    background.setAttribute("src","#egypt")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",true)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false) 
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", true)
    
    
}


function makeHawaii(){
    var background =document.getElementById('background')
    background.setAttribute("src","#hawaii")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",true)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",false)  
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", true)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
}

function makeIceland(){
    var background =document.getElementById('background')
    background.setAttribute("src","#iceland")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",true)
    document.getElementById('chicagoTitle').setAttribute("visible",false)
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
    
}

function makeDisney(){
    var background =document.getElementById('background')
    background.setAttribute("src","#disney")
    document.getElementById('earth').setAttribute("visible",false)
    document.getElementById('newYork').setAttribute("visible",false)
    document.getElementById('paris').setAttribute("visible",false)
    document.getElementById('sydney').setAttribute("visible",false)
    document.getElementById('backButton').setAttribute("visible",true)
    document.getElementById('backHomeButton').setAttribute("visible",false)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",false)   
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false) 
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('chicagoTitle').setAttribute("visible",true) 
    document.getElementById('plane').setAttribute("visible", false)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
    
    
}

function goBack(){
    var background =document.getElementById('background')
    background.setAttribute("src","#stars")
    document.getElementById('earth').setAttribute("visible",true)
    document.getElementById('newYork').setAttribute("visible",true)
    document.getElementById('paris').setAttribute("visible",true)
    document.getElementById('sydney').setAttribute("visible",true)
    document.getElementById('backButton').setAttribute("visible",false)
    document.getElementById('backHomeButton').setAttribute("visible",true)
    document.getElementById('newYorkTitle').setAttribute("visible",false)
    document.getElementById('parisTitle').setAttribute("visible",false)
    document.getElementById('sydneyTitle').setAttribute("visible",false)
    document.getElementById('fijiTitle').setAttribute("visible",false)
    document.getElementById('indonesiaTitle').setAttribute("visible",false)
    document.getElementById('columbiaTitle').setAttribute("visible",false)
    document.getElementById('trippyTitle').setAttribute("visible",true)  
    document.getElementById('chicagoTitle').setAttribute("visible",false)
    document.getElementById('icelandTitle').setAttribute("visible",false)
    document.getElementById('hawaiiTitle').setAttribute("visible",false)
    document.getElementById('egyptTitle').setAttribute("visible",false)
    document.getElementById('japanTitle').setAttribute("visible",false)
    document.getElementById('russiaTitle').setAttribute("visible",false)
    document.getElementById('newYorkText').setAttribute("visible",false)
    document.getElementById('sydneyText').setAttribute("visible",false)
    document.getElementById('parisText').setAttribute("visible",false)
    document.getElementById('indonesiaText').setAttribute("visible",false)
    document.getElementById('plane').setAttribute("visible", true)
    document.getElementById('fijiText').setAttribute("visible",false)
    document.getElementById('columbiaText').setAttribute("visible", false)
    document.getElementById('hawaiiText').setAttribute("visible", false)
    document.getElementById('japanText').setAttribute("visible", false)
    document.getElementById('egyptText').setAttribute("visible", false)
}
